### ISSUE TITLE
Uncaught Error: invalid keyPath

### ISSUE THREAD

**Issue by LeZuse** [blueberryapps/react-bluekit#46]
Still cannot get this to work in our stack. This is what I get in Chrome console when I launch the bluekit app:
```
Uncaught Error: invalid keyPath
invariant @ immutable.js:872
updateInDeepMap @ immutable.js:1976
updateInDeepMap @ immutable.js:1982
updateInDeepMap @ immutable.js:1982
updateInDeepMap @ immutable.js:1982
Map.updateIn @ immutable.js:1280
(anonymous function) @ immutable.js:4420
BitmapIndexedNode.iterate.HashArrayMapNode.iterate @ immutable.js:1739
BitmapIndexedNode.iterate.HashArrayMapNode.iterate @ immutable.js:1739
Map.__iterate @ immutable.js:1377
reduce @ immutable.js:4415
render @ Sidebar.react.js:67
render @ enhancer.js:132
_renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:687
_renderValidatedComponent @ ReactCompositeComponent.js:707
performInitialMount @ ReactCompositeComponent.js:291
mountComponent @ ReactCompositeComponent.js:222
mountComponent @ ReactReconciler.js:39
mountChildren @ ReactMultiChild.js:203
_createInitialChildren @ ReactDOMComponent.js:628
mountComponent @ ReactDOMComponent.js:474
mountComponent @ ReactReconciler.js:39
mountChildren @ ReactMultiChild.js:203
_createInitialChildren @ ReactDOMComponent.js:628
mountComponent @ ReactDOMComponent.js:474
mountComponent @ ReactReconciler.js:39
mountChildren @ ReactMultiChild.js:203
_createInitialChildren @ ReactDOMComponent.js:628
mountComponent @ ReactDOMComponent.js:474
mountComponent @ ReactReconciler.js:39
performInitialMount @ ReactCompositeComponent.js:297
mountComponent @ ReactCompositeComponent.js:222
mountComponent @ ReactReconciler.js:39
performInitialMount @ ReactCompositeComponent.js:297
mountComponent @ ReactCompositeComponent.js:222
mountComponent @ ReactReconciler.js:39
performInitialMount @ ReactCompositeComponent.js:297
mountComponent @ ReactCompositeComponent.js:222
mountComponent @ ReactReconciler.js:39
performInitialMount @ ReactCompositeComponent.js:297
mountComponent @ ReactCompositeComponent.js:222
mountComponent @ ReactReconciler.js:39
performInitialMount @ ReactCompositeComponent.js:297
mountComponent @ ReactCompositeComponent.js:222
mountComponent @ ReactReconciler.js:39
mountComponentIntoNode @ ReactMount.js:103
perform @ Transaction.js:136
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:136
batchedUpdates @ ReactDefaultBatchingStrategy.js:63
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:277
_renderSubtreeIntoContainer @ ReactMount.js:354
(anonymous function) @ app.js:61
(anonymous function) @ main.js:8340
(anonymous function) @ main.js:8341
__webpack_require__ @ bootstrap dcb2e9c…:555
fn @ bootstrap dcb2e9c…:86
(anonymous function) @ bootstrap dcb2e9c…:578
__webpack_require__ @ bootstrap dcb2e9c…:555
(anonymous function) @ bootstrap dcb2e9c…:578
(anonymous function) @ bootstrap dcb2e9c…:578
```

Will be happy to provide any more info if needed.

**Comment by ondrejbartas** [comment]
Do you have still this issue?

**Comment by LeZuse** [comment]
@ondrejbartas Yup, I haven't looked at it since then. Are there any updates that might address this?

**Comment by imtoo** [comment]
@LeZuse Sorry for the delay. It should be fixed within new version. Can you try it, please?

**Comment by LeZuse** [comment]
@imtoo Will try over the weekend

**Comment by LeZuse** [comment]
Still the same story unfortunately :(
![screenshot 2016-09-02 15 54 58](https://cloud.githubusercontent.com/assets/140393/18206141/a5347596-7125-11e6-8368-752d1b6c1268.png)

**Comment by mikekreeki** [comment]
The issue seems to be when working with directory structure like this one...

```js
components/
  shared/
    editor/
      SomeFancyEditor.react.js
    Editor.react.js
```

Looks like the bug is hidden when you have component and directory by the same name at the same time.

When generating the tree, `Components > Shared > Editor` key is already occupied by `ComponentsSharedEditor`, therefore you cannot `setIn` path like `["Components", "Shared", "Editor", "SomeFancyEditor."]` and error is thrown.

**Comment by ondrejbartas** [comment]
@mikekreeki thank you, we will look at this issue soon

**Comment by imtoo** [comment]
Fixed here #72
