### ISSUE TITLE
Console warnings relating to PropsTable

### ISSUE THREAD

**Issue by joshfarrant** [blueberryapps/react-bluekit#81]
I'm receiving the following errors when running the project:

Warning: Input: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)

Warning: Using Maps as children is not yet fully supported. It is an experimental feature that might be removed. Convert it to a sequence / iterable of keyed ReactElements instead. Check the render method of `PropsTable`.

Neither seem to be causing any concrete issues, however I am seeing odd behaviour with the enum dropdowns.

**Comment by imtoo** [comment]
Thanks for the feedback. The first warning with input is solved by v0.3.0. The second warning is solved in #89 so expect it in upcoming version.

What do you mean by odd behaviour with enum dropdowns?

**Comment by joshfarrant** [comment]
Fantastic, thanks.

I've still not nailed down the 'odd' enum dropdown behaviour, so bear with me here! Let's say I've got the following basic component:

```js
import React, { Component, PropTypes } from 'react';

const KIND = {
  PRIMARY: 'primary',
  SECONDARY: 'secondary'
};

class Button extends Component {

  static propTypes = {
    kind: PropTypes.oneOf([
      'primary',
      'secondary'
    ])
  };

  static defaultProps = {
    kind: KIND.PRIMARY
  }

  render() {
    const { kind } = this.props;

    return (
      <button>{kind}</button>
    );

  }
}

export default Button;
```

In this case, everything works as expected, and I get the following when I navigate to that component:

![Correct behaviour](http://imgur.com/wF5l8h3.png)

_Note that the 'kind' selector is a dropdown_

Now, if I make one small change to the `propTypes` (keeping everything else the same), you can see that the _'kind'_ selector is no longer a dropdown, but a text input.

```js
import React, { Component, PropTypes } from 'react';

const KIND = {
  PRIMARY: 'primary',
  SECONDARY: 'secondary'
};

class Button extends Component {

  static propTypes = {
    kind: PropTypes.oneOf(Object.values(KIND))
  };

  static defaultProps = {
    kind: KIND.PRIMARY
  }

  render() {
    const { kind } = this.props;

    return (
      <button>{kind}</button>
    );

  }
}

export default Button;
```

![Incorrect behaviour](http://imgur.com/SfqvPqm.png)

The thing that really throws me is that if I manually define an array containing the values from the `KIND` object and pass that to `PropTypes.oneOf()` everything works as expected and the _'kind'_ selector is once again a dropdown.

```js
// ...
const kindOptions = [
  'primary',
  'secondary'
];

class Button extends Component {

  static propTypes = {
    kind: PropTypes.oneOf(kindOptions)
  };

// ...
```

This lead me to think that the issue might be with how `Object.values` is implemented, but after looking a bit more into it that doesn't seem to be the case. Comparing the result of `Object.values(KIND)` with the `kindOptions` array shows that they are identical (Compared by `JSON.stringify()`ing both and comparing the strings). Also, I've tried building the array using a `for...in` loop, rather than `Object.values()`, but it doesn't fix the issue.

This one's left me scratching my head a bit, and I'm not entirely convinced that the issue is with BlueKit, but I wanted to mention it as it's doing my head in! It's not critical, but whatever the problem is does mean that the code I'm writing can't be quite as DRY.

**Comment by imtoo** [comment]
This is actually problem of react-docgen that is parsing all components. Because `Object.values(object)` is function which docgen cannot execute. So it returns string `"Object.values(object)"` and in this case it fallbacks to input.
